import bcrypt from 'bcrypt';

export async function seedAccounts(prisma) {
  const password = await bcrypt.hash('123456', 10);
  
  const accounts = [
    {
      username: 'admin',
      email: 'admin@farmerconnect.com',
      firstName: 'System',
      middleName: 'Super',
      surname: 'Admin',
      extensionName: null,
      access: 'Super_Admin',
      sex: 'Male',
      contactNumber: '09171234567',
      dateOfBirth: new Date('1985-01-15'),
      picturePath: 'accounts/admin.jpg',
      client_profile: 'Govt_Employee',
    },
    {
      username: 'user',
      email: 'user@farmerconnect.com',
      firstName: 'Test',
      middleName: null,
      surname: 'User',
      extensionName: null,
      access: 'User',
      sex: 'Male',
      contactNumber: '09171234568',
      dateOfBirth: new Date('1990-01-01'),
      picturePath: 'accounts/user.jpg',
      client_profile: 'Other',
    },
    {
      username: 'juan.delacruz',
      email: 'juan.delacruz@farmer.ph',
      firstName: 'Juan',
      middleName: 'Santos',
      surname: 'Dela Cruz',
      extensionName: null,
      access: 'User',
      sex: 'Male',
      contactNumber: '09181234567',
      dateOfBirth: new Date('1980-03-20'),
      picturePath: null,
      client_profile: 'Other',
    },
    {
      username: 'maria.santos',
      email: 'maria.santos@farmer.ph',
      firstName: 'Maria',
      middleName: 'Garcia',
      surname: 'Santos',
      extensionName: null,
      access: 'User',
      sex: 'Female',
      contactNumber: '09191234567',
      dateOfBirth: new Date('1992-07-10'),
      picturePath: null,
      client_profile: 'Women',
    },
    {
      username: 'pedro.reyes',
      email: 'pedro.reyes@farmer.ph',
      firstName: 'Pedro',
      middleName: 'Luna',
      surname: 'Reyes',
      extensionName: null,
      access: 'User',
      sex: 'Male',
      contactNumber: '09201234567',
      dateOfBirth: new Date('1975-11-05'),
      picturePath: null,
      client_profile: 'Other',
    },
    {
      username: 'ana.martinez',
      email: 'ana.martinez@farmer.ph',
      firstName: 'Ana',
      middleName: 'Cruz',
      surname: 'Martinez',
      extensionName: null,
      access: 'User',
      sex: 'Female',
      contactNumber: '09211234567',
      dateOfBirth: new Date('1988-05-18'),
      picturePath: null,
      client_profile: 'Women',
    },
    {
      username: 'jose.garcia',
      email: 'jose.garcia@farmer.ph',
      firstName: 'Jose',
      middleName: 'Ramos',
      surname: 'Garcia',
      extensionName: null,
      access: 'User',
      sex: 'Male',
      contactNumber: '09221234567',
      dateOfBirth: new Date('1990-09-12'),
      picturePath: null,
      client_profile: 'Other',
    },
    {
      username: 'rosa.fernandez',
      email: 'rosa.fernandez@farmer.ph',
      firstName: 'Rosa',
      middleName: 'Santos',
      surname: 'Fernandez',
      extensionName: null,
      access: 'User',
      sex: 'Female',
      contactNumber: '09231234567',
      dateOfBirth: new Date('1982-12-25'),
      picturePath: null,
      client_profile: 'Women',
    },
    {
      username: 'carlos.mendoza',
      email: 'carlos.mendoza@farmer.ph',
      firstName: 'Carlos',
      middleName: 'Torres',
      surname: 'Mendoza',
      extensionName: null,
      access: 'User',
      sex: 'Male',
      contactNumber: '09241234567',
      dateOfBirth: new Date('1998-04-08'),
      picturePath: null,
      client_profile: 'Youth',
    },
    {
      username: 'elena.torres',
      email: 'elena.torres@farmer.ph',
      firstName: 'Elena',
      middleName: 'Villanueva',
      surname: 'Torres',
      extensionName: null,
      access: 'User',
      sex: 'Female',
      contactNumber: '09251234567',
      dateOfBirth: new Date('1995-06-30'),
      picturePath: null,
      client_profile: 'Women',
    },
    {
      username: 'roberto.cruz',
      email: 'roberto.cruz@farmer.ph',
      firstName: 'Roberto',
      middleName: 'Bautista',
      surname: 'Cruz',
      extensionName: null,
      access: 'User',
      sex: 'Male',
      contactNumber: '09261234567',
      dateOfBirth: new Date('1970-02-14'),
      picturePath: null,
      client_profile: 'Other',
    },
  ];

  for (const accountData of accounts) {
    await prisma.account.upsert({
      where: { username: accountData.username },
      update: {},
      create: {
        ...accountData,
        password,
      },
    });
  }

  console.log(`✅ Created ${accounts.length} accounts (1 Super_Admin, ${accounts.length - 1} Users)`);
  console.log('📝 Quick Login: username=admin password=123456 OR username=user password=123456');
}
