import bcrypt from 'bcrypt';

export async function seedAccounts(prisma) {
  const password = await bcrypt.hash('123456', 10);
  
  const accounts = [
    {
      username: 'admin',
      email: 'admin@farmerconnect.com',
      firstName: 'System',
      surname: 'Admin',
      middleName: '',
      access: 'Super_Admin',
      sex: 'Other',
      mobileNumber: '09171234567',
      province: 'Laguna',
      municipality: 'Los Baños',
      barangay: 'Anos',
      region: 'Region IV-A',
      client_profile: 'Govt_Employee',
      education: 'College_graduate',
      dateOfBirth: new Date('1985-01-15'),
      civilStatus: 'Married',
    },
    {
      username: 'user',
      email: 'user@farmerconnect.com',
      firstName: 'Test',
      surname: 'User',
      middleName: '',
      access: 'User',
      sex: 'Male',
      mobileNumber: '09171234568',
      province: 'Laguna',
      municipality: 'Los Baños',
      barangay: 'Anos',
      region: 'Region IV-A',
      client_profile: 'Other',
      education: 'College_graduate',
      dateOfBirth: new Date('1990-01-01'),
      civilStatus: 'Single',
      isHouseholdHead: true,
      grossAnnualIncome: '100000-150000',
      incomeSource: 'farming',
    },
    {
      username: 'juan.delacruz',
      email: 'juan.delacruz@farmer.ph',
      firstName: 'Juan',
      surname: 'Dela Cruz',
      middleName: 'Santos',
      access: 'User',
      sex: 'Male',
      mobileNumber: '09181234567',
      province: 'Laguna',
      municipality: 'Bay',
      barangay: 'Bitin',
      region: 'Region IV-A',
      client_profile: 'Other',
      education: 'High_school_graduate',
      dateOfBirth: new Date('1980-03-20'),
      civilStatus: 'Married',
      spouseName: 'Maria Dela Cruz',
      isHouseholdHead: true,
      grossAnnualIncome: '150000-200000',
      incomeSource: 'farming',
    },
    {
      username: 'maria.santos',
      email: 'maria.santos@farmer.ph',
      firstName: 'Maria',
      surname: 'Santos',
      middleName: 'Garcia',
      access: 'User',
      sex: 'Female',
      mobileNumber: '09191234567',
      province: 'Laguna',
      municipality: 'Los Baños',
      barangay: 'Bayog',
      region: 'Region IV-A',
      client_profile: 'Women',
      education: 'College_graduate',
      dateOfBirth: new Date('1992-07-10'),
      civilStatus: 'Single',
      isHouseholdHead: false,
      householdHeadName: 'Pedro Santos',
      relationshipToHead: 'Daughter',
      grossAnnualIncome: '100000-150000',
      incomeSource: 'farming',
    },
    {
      username: 'pedro.reyes',
      email: 'pedro.reyes@farmer.ph',
      firstName: 'Pedro',
      surname: 'Reyes',
      middleName: 'Luna',
      access: 'User',
      sex: 'Male',
      mobileNumber: '09201234567',
      province: 'Laguna',
      municipality: 'Calauan',
      barangay: 'Balayhangin',
      region: 'Region IV-A',
      client_profile: 'Other',
      education: 'Elementary_graduate',
      dateOfBirth: new Date('1975-11-05'),
      civilStatus: 'Married',
      spouseName: 'Rosa Reyes',
      isHouseholdHead: true,
      grossAnnualIncome: '200000-250000',
      incomeSource: 'farming',
    },
    {
      username: 'ana.martinez',
      email: 'ana.martinez@farmer.ph',
      firstName: 'Ana',
      surname: 'Martinez',
      middleName: 'Cruz',
      access: 'User',
      sex: 'Female',
      mobileNumber: '09211234567',
      province: 'Laguna',
      municipality: 'Victoria',
      barangay: 'Banca-banca',
      region: 'Region IV-A',
      client_profile: 'Women',
      education: 'Senior_high_school_graduate',
      dateOfBirth: new Date('1988-05-18'),
      civilStatus: 'Married',
      spouseName: 'Jose Martinez',
      isHouseholdHead: false,
      relationshipToHead: 'Spouse',
      grossAnnualIncome: '150000-200000',
      incomeSource: 'farming',
    },
    {
      username: 'jose.garcia',
      email: 'jose.garcia@farmer.ph',
      firstName: 'Jose',
      surname: 'Garcia',
      middleName: 'Ramos',
      access: 'User',
      sex: 'Male',
      mobileNumber: '09221234567',
      province: 'Laguna',
      municipality: 'Pila',
      barangay: 'Aplaya',
      region: 'Region IV-A',
      client_profile: 'Other',
      education: 'Vocational_Technical',
      dateOfBirth: new Date('1990-09-12'),
      civilStatus: 'Single',
      isHouseholdHead: true,
      grossAnnualIncome: '100000-150000',
      incomeSource: 'farming',
    },
    {
      username: 'rosa.fernandez',
      email: 'rosa.fernandez@farmer.ph',
      firstName: 'Rosa',
      surname: 'Fernandez',
      middleName: 'Santos',
      access: 'User',
      sex: 'Female',
      mobileNumber: '09231234567',
      province: 'Laguna',
      municipality: 'San Pablo',
      barangay: 'San Buenaventura',
      region: 'Region IV-A',
      client_profile: 'Women',
      education: 'High_school_graduate',
      dateOfBirth: new Date('1982-12-25'),
      civilStatus: 'Widow',
      isHouseholdHead: true,
      grossAnnualIncome: '80000-100000',
      incomeSource: 'farming',
    },
    {
      username: 'carlos.mendoza',
      email: 'carlos.mendoza@farmer.ph',
      firstName: 'Carlos',
      surname: 'Mendoza',
      middleName: 'Torres',
      access: 'User',
      sex: 'Male',
      mobileNumber: '09241234567',
      province: 'Laguna',
      municipality: 'Nagcarlan',
      barangay: 'Buboy',
      region: 'Region IV-A',
      client_profile: 'Youth',
      education: 'College_graduate',
      dateOfBirth: new Date('1998-04-08'),
      civilStatus: 'Single',
      isHouseholdHead: false,
      householdHeadName: 'Roberto Mendoza',
      relationshipToHead: 'Son',
      grossAnnualIncome: '50000-80000',
      incomeSource: 'farming',
    },
    {
      username: 'elena.torres',
      email: 'elena.torres@farmer.ph',
      firstName: 'Elena',
      surname: 'Torres',
      middleName: 'Villanueva',
      access: 'User',
      sex: 'Female',
      mobileNumber: '09251234567',
      province: 'Laguna',
      municipality: 'Magdalena',
      barangay: 'Alipit',
      region: 'Region IV-A',
      client_profile: 'Women',
      education: 'Senior_high_school_graduate',
      dateOfBirth: new Date('1995-06-30'),
      civilStatus: 'Married',
      spouseName: 'Miguel Torres',
      isHouseholdHead: false,
      relationshipToHead: 'Spouse',
      grossAnnualIncome: '120000-150000',
      incomeSource: 'farming',
    },
    {
      username: 'roberto.cruz',
      email: 'roberto.cruz@farmer.ph',
      firstName: 'Roberto',
      surname: 'Cruz',
      middleName: 'Bautista',
      access: 'User',
      sex: 'Male',
      mobileNumber: '09261234567',
      province: 'Laguna',
      municipality: 'Liliw',
      barangay: 'Bagong Anyo',
      region: 'Region IV-A',
      client_profile: 'Other',
      education: 'Elementary_graduate',
      dateOfBirth: new Date('1970-02-14'),
      civilStatus: 'Married',
      spouseName: 'Carmen Cruz',
      isHouseholdHead: true,
      grossAnnualIncome: '180000-200000',
      incomeSource: 'farming',
    },
  ];

  for (const accountData of accounts) {
    await prisma.account.upsert({
      where: { username: accountData.username },
      update: {},
      create: {
        ...accountData,
        password,
      },
    });
  }

  console.log(`✅ Created ${accounts.length} accounts (1 Super_Admin, ${accounts.length - 1} Users)`);
  console.log('📝 Quick Login: username=admin password=123456 OR username=user password=123456');
}
