flowchart TB

    subgraph "--"

        subgraph "ADMIN"
            UC1[View All Users]
            UC2[Edit User Details]
            
            UC4[Delete User Account]
            UC5[Reset User Password]
            UC6[Create Seminar]
            UC7[Edit Seminar Details]
            UC8[Upload Seminar Media]
            UC9[Manage Participants]
        end
            
        A1[Administrator]
        
        subgraph "ADMIN"
            UC3[Manage User Roles] 
            UC10[Mark Attendance]
            UC11[Cancel Seminar]
            UC12[View System Statistics]
            UC13[Generate Reports]
            UC14[Monitor User Activity]
            UC15[Track System Performance]
        end

    end

    A1 --- UC10
    A1 --- UC11
    A1 --- UC12
    A1 --- UC13
    A1 --- UC14
    A1 --- UC15
    A1 --- UC3

    UC8 <--- A1
    UC9 <--- A1
    UC1 <--- A1
    UC2 <--- A1
    UC4 <--- A1
    UC5 <--- A1
    UC6 <--- A1
    UC7 <--- A1
    
  
    