%%{init: {
  'theme': 'base',
  'themeVariables': {
    'primaryColor': '#ffffff',
    'primaryTextColor': '#000000',
    'primaryBorderColor': '#000000',
    'lineColor': '#000000',
    'secondaryColor': '#f8f8f8',
    'tertiaryColor': '#ffffff',
    'background': '#ffffff',
    'mainBkg': '#ffffff',
    'secondBkg': '#f8f8f8',
    'tertiaryTextColor': '#000000'
  }
}}%%
flowchart TB
     subgraph "--"


        subgraph "INVENTORY"
            UC1[Add Inventory Item]
            UC2[Edit Item Details]
            UC3[Delete Item]
            UC4[Upload Item Images]
            UC5[Categorize Items]
            UC6[Create Item Stacks]
            UC7[Edit Stack Quantities]
            UC8[Update Stack Status]
        end
        
        A2[Super Admin]
        A1[Administrator]

        subgraph "INVENTORY"
            UC9[Transfer Stack Items]
            UC10[Delete Stack]
            UC11[Review EIC Requests]
            UC12[Approve/Reject EIC]
            UC13[Review Distribution Requests]
            UC14[Approve/Reject Distribution]
            UC15[Schedule Pickups]
            UC16[Track Returns]
            
        end

    end
    
    
    A1 --- UC9
    A1 --- UC10
    A1 --- UC11
    A1 --- UC12
    A1 --- UC13
    A1 --- UC14
    A1 --- UC15
    A1 --- UC16
    
    UC1 <--- A1
    UC2 <--- A1
    UC3 <--- A1
    UC4 <--- A1
    UC5 <--- A1
    UC6 <--- A1
    UC7 <--- A1
    UC8 <--- A1

    A2 ---> UC1
    A2 ---> UC2
    A2 ---> UC3

   

    
    
